spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polixia_auth_db?createDatabaseIfNotExist=true
    username: root
    password: tiger
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}-${random.int}

